### ISSUE TITLE
No Main  manifest attribut error

### ISSUE THREAD

**Issue by flenoir** [noophq/subtitle#5]
Hi, 

 I did the package  but when i want to run java -jar subtitle-*.jar -i input-file -o output-file , 

 i have an error : "No Main  manifest attribut error"

 is the jar an executable ? 

 thanks

**Comment by clebeaupin** [comment]
Hi,

Yes it is but you need to take the one with dependencies : java -jar target/subtitle-0.9.0-jar-with-dependencies.jar

I have to change it include all the stuff in the main jar
